apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-kubernetes-discovery-sample
  labels:
    # spring-cloud-kubernetes-configuration-watcher 监听 label
    spring.cloud.kubernetes.config: "true"
data:
  application.yml: |-
    feign:
      client:
        config-sample-url: http://configsample.anchnet.com
    ---
    spring:
      config:
        activate:
          on-profile: kubernetes
    feign:
      client:
        config-sample-url: http://spring-cloud-kubernetes-config-sample:8080