apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-kubernetes-gateway-sample
  labels:
    # spring-cloud-kubernetes-configuration-watcher 监听 label
    spring.cloud.kubernetes.config: "true"
data:
  application.yml: |-
    spring:
      config:
        activate:
          on-profile: default
        import: optional:configserver:http://configserver.anchnet.com
      cloud:
        kubernetes:
          discovery:
            discovery-server-url: http://discoveryserver.anchnet.com
    
    ---
    spring:
      config:
        activate:
          on-profile: kubernetes
          # on-cloud-platform: kubernetes
        import: optional:configserver:http://spring-cloud-kubernetes-configserver:8888
      cloud:
        kubernetes:
          discovery:
            discovery-server-url: http://spring-cloud-kubernetes-discoveryserver