spring:
  config:
    activate:
      on-profile: kubernetes
    import: configserver:http://spring-cloud-kubernetes-configserver:8888

greeting:
  message: HelloWorld! --- from application-kubernetes.yml

secret:
  username: kubernetes
  password: 222222