server:
  port: 9080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-kubernetes-discovery-sample
  jackson:
    serialization:
      fail-on-empty-beans: false

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
#  health:
#    kubernetes:
#      enabled: false
#  info:
#    kubernetes:
#      enabled: false

logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.cloud.openfeign: TRACE